apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-html
  namespace: hw-ns
data:
  index.html: |
    <html>
      <body style="background-color: #4CAF50; color: white; text-align: center; font-family: sans-serif; padding-top: 50px;">
        <h2>Hello World!</h2>
        <p><h1>This page is served from a Kubernetes ConfigMap!</h1></p>  
        <p>Managed by ArgoCD via GitOps</p>
      </body>
    </html>
