apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/isaradhi24/kubadmin-labs.git'
    targetRevision: HEAD
    path: apps/Microservices-app/Microservice1
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true