apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ns



# Create  namespaces nginx-ns
# kubectl apply -f namespace.yaml

# List namespaces
# kubectl get ns

# Use a namespace
# kubectl config set-context --current --namespace=nginx-ns 
#       ---> set the current context to use the nginx-ns namespace

# Verify the current namespace
# kubectl config view --minify | grep namespace:  
#       ---> should show namespace: nginx-ns
