apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-lab
  template:
    metadata:
      labels:
        app: hello-lab
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80