name: CI-Nginx-ArgoCD
on: 
  push:
    branches: [ main ]
    paths: 
      - 'apps/my-nginix-app/**' # Only trigger if the ArgoCD application manifest changes
      - 'infra/manifests/nginx-app-config.yaml' # Also trigger if there is changes infra manifest changes

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl get nodes 
      - name: Update ArgoCD Application
        run: |
          export KUBECONFIG=$PWD/kubeconfig

          echo "ArgoCD has received the update."