name: CI Pipeline
on: [push]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Update ArgoCD Application
        run: | 
           # We ONLY apply the 'manager' file. 
           # We do NOT apply the apps/my-nginx-app/manifests/ folder here!
           kubectl apply -f argocd-nginx-app.yaml
           
           echo "ArgoCD has received the update. Check the UI for namespace creation and deployment."