name: CI Pipeline
on: [push]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 👇 ADD THIS STEP
      - name: Setup kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl get nodes   # optional debug

      - name: Update ArgoCD Application
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl apply -f argocd-nginx-app.yaml

          echo "ArgoCD has received the update."